apiVersion: v1
kind: Service
metadata:
  name: devops-python-service
spec:
  type: Nodeport
  selector:
    app: devops-python-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
